src/MvcAppExample.Web/Controllers/TestarLogsController.cs
using log4net;
using MvcAppExample.Application.Interfaces;
using System;
using System.Web.Mvc;

namespace MvcAppExample.Web.Controllers
{
    public class TestarLogsController : Controller
    {
        IContatoAppService _contatoAppService;

        public TestarLogsController(IContatoAppService contatoAppService)
        {
            _contatoAppService = contatoAppService;
        }

        public ActionResult Index()
        {
            var teste = _contatoAppService.GetAll();

            var logger = LogManager.GetLogger(typeof(TestarLogsController));
            logger.Warn("Atenção ...vai dar erro");

            throw new Exception("Parabéns! Você gerou uma exceção");
        }
    }
}

src/MvcAppExample.Web/Controllers/UsuariosController.cs
using MvcAppExample.Application.Interfaces;
using System.Web.Mvc;

namespace MvcAppExample.Web.Controllers
{
    [Authorize]
    public class UsuariosController : Controller
    {
        private readonly IUsuarioAppService _usuarioAppService;

        public UsuariosController(IUsuarioAppService usuarioAppService)
        {
            _usuarioAppService = usuarioAppService;
        }

        public ActionResult Index()
        {
            return View(_usuarioAppService.ObterTodos());
        }

        public ActionResult Details(string id)
        {
            return View(_usuarioAppService.ObterPorId(id));
        }

        public ActionResult DesativarLock(string id)
        {
            _usuarioAppService.DesativarLock(id);
            return RedirectToAction("Index");
        }
    }
}

src/MvcAppExample.Web/Views/Shared/AccessDenied.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Acesso Negado!";
}

<h1 class="text-danger">Acesso Negado :(</h1>
<h2 class="text-danger">Você não tem permissão para fazer isso.</h2>

src/MvcAppExample.Web/Views/Shared/NotFound.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Página não encontrada!";
}

<h1 class="text-danger">Página não encontrada :(</h1>
<h2 class="text-danger">A página que você está procurando não existe.</h2>

src/MvcAppExample.Web/Views/Shared/_ErrorSummary.cshtml
@if (ViewData.ModelState[""] != null && ViewData.ModelState[""].Errors.Any())
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dissmiss="alert">x</button>
        <h3>Atenção!</h3>
        @Html.ValidationSummary(true);
    </div>
}

@if (!string.IsNullOrEmpty(ViewBag.Sucesso))
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dissmiss="alert">x</button>
        <h3>@ViewBag.Sucesso</h3>
    </div>
}

src/MvcAppExample.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Contatos", "Index", "Contatos")</li>
                    <li>@Html.ActionLink("Testar Logs", "Index", "TestarLogs")</li>
                    <li>@Html.ActionLink("Lista Usuários", "Index", "Usuarios")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>